# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import wordservice_pb2 as wordservice__pb2


class WordServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DefineWord = channel.unary_unary(
        '/endpoints.word_service.WordService/DefineWord',
        request_serializer=wordservice__pb2.DefineWordRequest.SerializeToString,
        response_deserializer=wordservice__pb2.DefineWordResponse.FromString,
        )


class WordServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DefineWord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WordServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DefineWord': grpc.unary_unary_rpc_method_handler(
          servicer.DefineWord,
          request_deserializer=wordservice__pb2.DefineWordRequest.FromString,
          response_serializer=wordservice__pb2.DefineWordResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'endpoints.word_service.WordService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
