# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: wordservice.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import wordservice_pb2


class WordServiceBase(abc.ABC):

    @abc.abstractmethod
    async def DefineWord(self, stream: 'grpclib.server.Stream[wordservice_pb2.DefineWordRequest, wordservice_pb2.DefineWordResponse]') -> None:
        pass

    @abc.abstractmethod
    async def WordFromDefinition(self, stream: 'grpclib.server.Stream[wordservice_pb2.WordFromDefinitionRequest, wordservice_pb2.WordFromDefinitionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GenerateWord(self, stream: 'grpclib.server.Stream[wordservice_pb2.GenerateWordRequest, wordservice_pb2.GenerateWordResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/endpoints.word_service.WordService/DefineWord': grpclib.const.Handler(
                self.DefineWord,
                grpclib.const.Cardinality.UNARY_UNARY,
                wordservice_pb2.DefineWordRequest,
                wordservice_pb2.DefineWordResponse,
            ),
            '/endpoints.word_service.WordService/WordFromDefinition': grpclib.const.Handler(
                self.WordFromDefinition,
                grpclib.const.Cardinality.UNARY_UNARY,
                wordservice_pb2.WordFromDefinitionRequest,
                wordservice_pb2.WordFromDefinitionResponse,
            ),
            '/endpoints.word_service.WordService/GenerateWord': grpclib.const.Handler(
                self.GenerateWord,
                grpclib.const.Cardinality.UNARY_UNARY,
                wordservice_pb2.GenerateWordRequest,
                wordservice_pb2.GenerateWordResponse,
            ),
        }


class WordServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DefineWord = grpclib.client.UnaryUnaryMethod(
            channel,
            '/endpoints.word_service.WordService/DefineWord',
            wordservice_pb2.DefineWordRequest,
            wordservice_pb2.DefineWordResponse,
        )
        self.WordFromDefinition = grpclib.client.UnaryUnaryMethod(
            channel,
            '/endpoints.word_service.WordService/WordFromDefinition',
            wordservice_pb2.WordFromDefinitionRequest,
            wordservice_pb2.WordFromDefinitionResponse,
        )
        self.GenerateWord = grpclib.client.UnaryUnaryMethod(
            channel,
            '/endpoints.word_service.WordService/GenerateWord',
            wordservice_pb2.GenerateWordRequest,
            wordservice_pb2.GenerateWordResponse,
        )
